# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_fcm', '0004_auto_20170320_0429'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('user', 'device_id')]),
        ),
    ]
